# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  containers:
    - container: pg11
      image: postgres:11
      ports: 
      - 6432:5432
      env:
        POSTGRES_PASSWORD: admin

pool:
  vmImage: 'ubuntu-latest'

services:
  pg11: pg11

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'server/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
