# Google cloud run will use PORT environmental variable to bootstrap app
app:
  name: tuzhub-api
  port: ${PORT:8090}

tuzhub:
  enableRemoteUpdates: ${REMOTE_UPDATE:false}

##
## Postgres setup - To use local docker instance see src/test/main/StartPostgresDocker.main()
##
ebean:
  dbSchema: tuzzy_portal
  migration:
    run: true

datasource:
  db:
    username: ${DB_USER:tuzzy_portal}
    password: ${DB_PASSWORD:test}
    url: ${DB_URL:jdbc:postgresql://localhost:7432/tuzzy_portal}
    driver: ${DB_DRIVER:org.postgresql.Driver}
